# For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.
[package]
name = "open-orphanage-chirho"
version = "0.1.0"
edition = "2021"
authors = ["LoveJesus <loveJesus@loveJes.us"]
description = "OpenOrphanageChirho - A platform for managing orphanages and child sponsorship"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.5.0", features = ["d1"] }
axum = { version = "~0.8.4", default-features = false, features = ["json", "macros"] }
axum-wasm-macros = "^0.1.2"
axum-cloudflare-adapter = { version = "~0.14.0" }
tower-service = "~0.3.3"
url = "2.5.4"
oneshot = { version = "~0.1.11" }
wasm-bindgen-futures = "~0.4.50"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.16.0", features = ["v4", "serde", "js"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken-rustcrypto = { version="~1.2.0" }
argon2 = { version = "~0.5.3" }
wasm-bindgen = { version = "~0.2.100", features = ["serde-serialize"] }
regex = "~1.11.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
web-sys = { version = "~0.3.77", features = [
    "Headers",
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Window",
    "console"
]}
getrandom = { version = "~0.2", features = ["js"] }
serde-wasm-bindgen = "0.6"
js-sys = "0.3"
cfg-if = "1.0.0"

#js-sys = "~0.3.77"
#console_error_panic_hook = "0.1.7"
#console_log = "1.0.0"
#thiserror = "1.0.69"

[dev-dependencies]
tokio-test = "~0.4.4"
mockall = "~0.12.1"


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[package.metadata.release]
release = false

# https://github.com/rustwasm/wasm-pack/issues/1247
[package.metadata.wasm-pack.profile.release]
wasm-opt = false
